version: '3.1'

services:
  mysql_db:
    image: mysql:8.2.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: otus
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./dbdata:/var/lib/mysql/
  social_network_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ivrudnev/social-network:1.0.0
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_DATABASE: otus
      MYSQL_USERNAME: admin
      MYSQL_PASSWORD: admin