spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    change-log: classpath:db/changelog/changelog-init.yaml